version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=todos
    depends_on:
      - db

  frontend:
    build: ./frontend/todo-app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: